name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: npm test

      - name: Increment version and tag
        id: version_increment
        run: |
          if [[ ! -z "${{ github.event.head_commit.message }}" && ! ${{ contains(github.event.head_commit.message, '[skip ci]') }} ]]; then
            VERSION=$(npm version patch --no-git-tag | cut -d ' ' -f 2)
            echo "::set-output name=new_version::$VERSION"
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add package.json
            git commit -m "chore: Release $VERSION"
            git tag $VERSION
            git push origin $VERSION
            git push origin main
            echo "::set-output name=version_bumped::true" # Set version_bumped to true
          else
            echo "Version bump skipped."
            echo "::set-output name=version_bumped::false" # Set version_bumped to false
          fi

      - name: Build Docker image
        if: steps.version_increment.outputs.version_bumped == 'true' # Correct condition
        run: |
          VERSION=${{ steps.version_increment.outputs.new_version }}
          docker build --build-arg VERSION=$VERSION -t your-registry/your-service:$VERSION .
          docker push your-registry/your-service:$VERSION

      - name: Deploy (example with Docker Compose)
        if: steps.version_increment.outputs.version_bumped == 'true' # Correct condition
        run: |
          VERSION=${{ steps.version_increment.outputs.new_version }}
          sed -i "s/your-registry\/your-service:.*$/your-registry\/your-service:$VERSION/g" docker-compose.yml
          docker-compose up -d
